-- À exécuter une seule fois dans Supabase : SQL Editor.
create extension if not exists vector;

create table if not exists public.users (
  phone_number text primary key,
  role text check (role in ('etudiant', 'chercheur')),
  step text not null default 'awaiting_role'
    check (step in ('awaiting_role', 'active')),
  created_at timestamptz not null default now()
);

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  user_id text not null,
  content text not null,
  page integer,
  embedding vector(384) not null,
  created_at timestamptz not null default now()
);

create index if not exists documents_embedding_idx
  on public.documents using ivfflat (embedding vector_cosine_ops) with (lists = 100);
create index if not exists documents_user_id_idx on public.documents (user_id);

create or replace function public.match_documents(
  query_embedding vector(384),
  match_user_id text,
  match_count integer default 5
)
returns table(content text, page integer, similarity float)
language sql stable
as $$
  select d.content, d.page, 1 - (d.embedding <=> query_embedding) as similarity
  from public.documents d
  where d.user_id = match_user_id
  order by d.embedding <=> query_embedding
  limit match_count;
$$;
